language: node_js
node_js:
  - 8

# command to install dependencies
install: "npm install"

cache:
  directories:
    - "node_modules"

# scripts run as part of build
scripts:
    - npm test

after_success:
  - npm install codecov -g
  - codecov
  - nyc report --reporter=json > coverage/coverage.json